#禁用默认处理页面
server:
  error:
    whitelabel:
      enabled: false
#配置默认的数据库连接池
spring:
  druid:
    borrowConnectionTimeout: 30000
    maxActive: 20
    maxWait: 10000
    minEvictableIdleTimeMillis: 300000
    minIdle: 3
    password: root
    timeBetweenEvictionRunsMillis: 60000
    url: jdbc:mysql://127.0.0.1:3306/house?useSSL=true
    username: root
    validationQuery: SELECT 'x' # 解决mysql8小时问题
  redis:
    password: redis-01
    cluster:
     nodes:
       - 192.168.100.170:7000
       - 192.168.100.170:7001
       - 192.168.100.171:7000
       - 192.168.100.171:7001
       - 192.168.100.172:7000
       - 192.168.100.172:7001
    timeout: 60s
mapper:
  not-empty: true
  identity: MYSQL
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  level:
    com.ruanmou.house.houseserver.mapper: debug
